# redis.conf

maxmemory 128mb

# allkeys-lru: удалять наименее недавно использованные ключи (любые)
# volatile-lru: удалять наименее недавно использованные ключи ТОЛЬКО с TTL (наш случай!)
maxmemory-policy volatile-lru

notify-keyspace-events "EAx"

save 900 1
save 300 10
save 60 10000

loglevel notice